public class cvgCsvClassMember 
{ 
    @Auraenabled public string Name    { get;set; } 
    @Auraenabled public String SalesDesk   { get;set; }
    @Auraenabled  public string SalesCode {get;set;}
    @Auraenabled  public String SalesDeskRegion {get;set;}
    @Auraenabled  public Date CoverageStartDate {get;set;}
    @Auraenabled public String Comment {get;set;}
    @Auraenabled public String Role {get;set;}
    @AuraEnabled public String Region {get;set;}
    @AuraEnabled public String Product {get;set;}
    @AuraEnabled public String Division {get;set;}
   @AuraEnabled public String Type {get;set;}
}