@isTest
private class DeploymentHelperTest {
    
	@isTest
    private static void testDeploymentStatus(){
        DeploymentHelper.testDeploymentStatus();
    } 
    
    @isTest
    private static void testDeploymentStatus2(){
        DeploymentHelper.testDeploymentStatus2();
    }
    
    @isTest
    private static void testDeploymentStatus3(){
        DeploymentHelper.testDeploymentStatus3();
    }
    
    
}